[package]
name = "vinculum-benchmark"
version = "0.1.0"
authors = ["Eric Niklas Wolf <robo-eric@gmx.de>"]
description = "Simple frontend for benchmark purposes"
readme = "README.md"
repository = "https://github.com/Deric-W/vinculum"
license = "LGPL-2.1-only"
keywords = ["backup", "deduplication"]
categories = ["database-implementations"]
edition = "2021"

[dependencies]
futures = "0.3"
serde = {version = "1.0", features = ["derive"] }
clap = { version = "4.5.26", features = ["derive"] }
hex = "0.4.3"
tokio = { version = "1", features = ["rt", "sync"] }
tokio-stream = "0.1.16"
vinculum = { path = "../..", features = ["files", "serde"] }
ciborium = "0.2.2"
sha2 = "0.10"

[dev-dependencies]
assert_cmd = "2.0.16"
tokio = { version = "1", features = ["macros", "rt"] }
tempfile = "3"
