name: CI
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

# two different jobs since if conditions can't access matrix values
jobs:
  test_stable:
    name: Build & Test (stable)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: stable
        components: rustc, rust-std, cargo, rustfmt, clippy
        cache: false
  
    - name: Setup Cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: stable

    - name: Lint
      run: |
        cargo fmt --all --check
        cargo clippy -- -D warnings

    - name: Install Tarpaulin
      run: cargo install cargo-tarpaulin --no-default-features

    - name: Build & Test (with coverage)
      run: cargo tarpaulin --verbose --all-features --engine llvm --out xml

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        flags: ${{ runner.os }}
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  test_beta:
    name: Build & Test (beta)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: beta
        components: rustc, rust-std, cargo, rustfmt, clippy
        cache: false
  
    - name: Setup Cache
      uses: Swatinem/rust-cache@v2
      with:
        shared-key: beta

    - name: Lint
      run: |
        cargo fmt --all --check
        cargo clippy -- -D warnings

    - name: Build & Test (without coverage)
      run: cargo test --verbose --all-features
